/**
 * apps/api-gateway/src/modules/auth/services/jwt-verifier.service.ts
 *
 * Verify access JWTs issued by core-api (SaasCheckin.Domain.Identity.Services.JwtTokenService).
 * Algorithm: RS256, 2048-bit. Public key cached in Redis at `jwt:signing:key`
 * as JSON `{ publicPem: "-----BEGIN PUBLIC KEY-----..." }`.
 *
 * Issuer: saas-checkin-core-api
 * Audience: web (tenant) | checkin-admin (platform — I-106+)
 */
import { Inject, Injectable, Logger, UnauthorizedException } from "@nestjs/common";
import { importSPKI, jwtVerify, type JWTPayload } from "jose";
import type Redis from "ioredis";
import { REDIS } from "../../_shared/redis/redis.module";

const SIGNING_KEY_CACHE_KEY = "jwt:signing:key";
const ISSUER = "saas-checkin-core-api";
const AUDIENCE_WEB = "web";
const AUDIENCE_PLATFORM = "checkin-admin";

interface CachedSigningKeyMaterial {
  // Accept both camelCase (preferred) and PascalCase (older .NET serialization) keys
  // for backward compatibility with previously-cached key material.
  keyId?: string;
  publicPem?: string;
  privatePem?: string;
  createdAt?: string;
  // PascalCase fallbacks
  KeyId?: string;
  PublicPem?: string;
  PrivatePem?: string;
  CreatedAt?: string;
}

export interface VerifiedAuth {
  sub: string;        // user id (UUID)
  email: string;
  fullName: string;
  tenantId?: string;  // current tenant from claim (web audience only)
  role?: string;      // web: tenant role | platform: platform role string
  permissions: string[];
  jti: string;
  // Platform audience (aud=checkin-admin) extras
  platformRole?: string;  // e.g. "platform_owner"
  mfaEnabled?: boolean;
}

@Injectable()
export class JwtVerifierService {
  private readonly logger = new Logger(JwtVerifierService.name);
  private cachedKey: { pem: string; importedAt: number } | null = null;
  private static readonly CACHE_TTL_MS = 5 * 60 * 1000; // 5 min in-memory

  constructor(@Inject(REDIS) private readonly redis: Redis) {}

  async verify(token: string, audience: string = AUDIENCE_WEB): Promise<VerifiedAuth> {
    const pem = await this.getPublicKey();
    const publicKey = await importSPKI(pem, "RS256");
    try {
      const { payload } = await jwtVerify(token, publicKey, {
        issuer: ISSUER,
        audience,
        algorithms: ["RS256"],
      });
      return this.toVerifiedAuth(payload);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "JWT verification failed";
      this.logger.debug(`JWT verify failed: ${msg}`);
      throw new UnauthorizedException("Invalid or expired token");
    }
  }

  private toVerifiedAuth(payload: JWTPayload): VerifiedAuth {
    const sub = (payload.sub ?? "") as string;
    const email = (payload["email"] ?? "") as string;
    const fullName = (payload["full_name"] ?? "") as string;
    const tenantId = (payload["tenant_id"] ?? undefined) as string | undefined;
    const role = (payload["role"] ?? undefined) as string | undefined;
    const jti = (payload["jti"] ?? "") as string;
    const perms = (payload["permission"] ?? []) as string | string[];
    const permissions = Array.isArray(perms) ? perms : [perms];

    // Platform-admin audience extras (I-107)
    const mfaClaim = payload["mfa"];
    const mfaEnabled = typeof mfaClaim === "string" ? mfaClaim === "true" : mfaClaim === true;
    const platformRole = (payload["role"] ?? undefined) as string | undefined;

    if (!sub) throw new UnauthorizedException("JWT missing 'sub' claim");
    const result: VerifiedAuth = { sub, email, fullName, tenantId, role, permissions, jti };
    // Set mfaEnabled = false explicitly (omitting means "not applicable"); UI distinguishes.
    if (mfaClaim !== undefined) result.mfaEnabled = mfaEnabled;
    // platformRole same string as role; expose separately để UI dùng dễ
    if (platformRole && !tenantId) result.platformRole = platformRole;
    return result;
  }

  private async getPublicKey(): Promise<string> {
    // In-memory cache first
    if (this.cachedKey && Date.now() - this.cachedKey.importedAt < JwtVerifierService.CACHE_TTL_MS) {
      return this.cachedKey.pem;
    }

    // Read from Redis (core-api caches at this key)
    const raw = await this.redis.get(SIGNING_KEY_CACHE_KEY);
    if (!raw) {
      throw new UnauthorizedException(
        "JWT signing key not yet generated by core-api. " +
          "Wait for the first user to sign in, or ensure core-api is running.",
      );
    }

    let material: CachedSigningKeyMaterial;
    try {
      material = JSON.parse(raw) as CachedSigningKeyMaterial;
    } catch {
      throw new UnauthorizedException("Corrupt signing key material in Redis");
    }

    const pem = material.publicPem ?? material.PublicPem;
    if (!pem || typeof pem !== "string") {
      this.logger.error(
        `Signing key material missing publicPem. Keys present: ${Object.keys(material).join(",")}`,
      );
      throw new UnauthorizedException("Signing key material missing publicPem");
    }
    this.logger.debug(
      `Public key length=${pem.length} starts=${JSON.stringify(pem.substring(0, 40))}`,
    );
    this.cachedKey = { pem, importedAt: Date.now() };
    return pem;
  }

  /** Strip PEM headers/whitespace, jose sometimes barfs on edge whitespace. */
  private stripPem(p: string): string {
    return p.replace(/-----BEGIN[^-]+-----/g, "").replace(/-----END[^-]+-----/g, "").replace(/\s+/g, "");
  }
}
