<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SaasCheckin.Application.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\shared\Shared.Application.Contracts\Shared.Application.Contracts.csproj" />
    <ProjectReference Include="..\SaasCheckin.Domain\SaasCheckin.Domain.csproj" />
  </ItemGroup>
</Project>
