<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SaasCheckin.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\shared\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\SaasCheckin.Application.Contracts\SaasCheckin.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
