<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SaasCheckin.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <ProjectReference Include="..\SaasCheckin.Application\SaasCheckin.Application.csproj" />
    <ProjectReference Include="..\SaasCheckin.EntityFrameworkCore\SaasCheckin.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
