<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SaasCheckin.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" />
    <ProjectReference Include="..\SaasCheckin.Application\SaasCheckin.Application.csproj" />
    <ProjectReference Include="..\SaasCheckin.EntityFrameworkCore\SaasCheckin.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
